[params.author]
name = 'ECC Computing Club Contributors'
image = '/images/club-logo.png'
headline = ''
bio = ''
links = [
	{ github = 'https://github.com/hyperupcall' },
	{ bluesky = 'https://bsky.app/profile/hyperupcall.bsky.social' },
]

[params.footer]
showCopyright = false
