[params.author]
name = "Edwin Kofler"
image = "images/edwin-kofler.jpg"
headline = ""
bio = "I like to build things with code."
links = [
  { github = "https://github.com/hyperupcall" },
  { bluesky = 'https://bsky.app/profile/hyperupcall.bsky.social' },
]
