[params.author]
name = 'ECC Computing Club Contributors'
image = '/images/club-logo.png'
headline = ''
bio = ''
links = [
	{ github = 'https://github.com/hyperupcall' },
	{ github = 'https://github.com/shubhangibw' }
]

[params.footer]
showCopyright = false
