[[main]]
  name = 'Home'
  pageRef = '_index'
  weight = 10

[[main]]
  name = 'Events'
  pageRef = 'events'
  weight = 20

[[main]]
  name = 'Resources'
  pageRef = 'resources'
  weight = 25

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 30

[[main]]
  name = 'About'
  pageRef = 'about'
  weight = 40

[[main]]
  # name = "Topics"
  # pageRef = "topics"
  # weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/ecc-cs-club/website"
  weight = 95
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 98
  [main.params]
    action = "search"
    icon = "search"

# [[footer]]
#   name = "Privacy"
#   pageRef = "privacy"
#
