name: "GitHub Pages"

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-24.04"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Install Hugo"
        run: |
          set -e
          version='0.145.0'
          curl -sSLf -o '${{ runner.temp }}/hugo.deb' "https://github.com/gohugoio/hugo/releases/download/v${version}/hugo_extended_${version}_linux-amd64.deb"
          sudo dpkg -i '${{ runner.temp }}/hugo.deb'
      - run: "hugo mod get"
      - run: "hugo --minify"
      - name: "Upload Artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: ./public

  deploy:
    name: "Deploy"
    runs-on: "ubuntu-24.04"
    needs: ["build"]
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
